# Generated by Django 4.0.5 on 2022-06-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=256)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comissao', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=256)),
                ('CPF', models.CharField(max_length=14)),
                ('data_admissao', models.DateField(auto_now_add=True)),
                ('comissao', models.BooleanField(default=False)),
                ('cargo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.cargo')),
            ],
        ),
    ]
