# Generated by Django 4.0.5 on 2022-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_funcionario_data_admissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
